#** Load the dataset and basic inspection**

In [2]:
import pandas as pd

df = pd.read_csv("/content/EMI_dataset.csv")

In [3]:
df.head()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,...,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,49,Female,Married,Post Graduate,110487,Government,26,Government,Rented,39303,...,1,34061,577,188826,33590,E-commerce,56153,18,High_Risk,1642
1,25,Male,Married,Professional,188297,Government,13,Government,Family,0,...,0,0,680,1316145,454773,E-commerce,151932,12,High_Risk,50000
2,43,Female,Single,Professional,179994,Private,34,Government,Own,0,...,0,0,593,915670,196193,E-commerce,157131,24,High_Risk,50000
3,58,Male,Single,Post Graduate,87957,Private,11,Startup,Family,0,...,0,0,664,126513,33782,Home Appliances,44076,16,High_Risk,13892
4,48,Female,Married,Graduate,21359,Private,4,Large,Own,0,...,1,2996,811,53742,7421,Personal Loan,541447,43,Not_Eligible,500

In [4]:
df.shape

(400000, 27)

In [5]:
df.columns

Index(['age', 'gender', 'marital_status', 'education', 'monthly_salary',
       'employment_type', 'years_of_employment', 'company_type', 'house_type',
       'monthly_rent', 'family_size', 'dependents', 'school_fees',
       'college_fees', 'travel_expenses', 'groceries_utilities',
       'other_monthly_expenses', 'existing_loans', 'current_emi_amount',
       'credit_score', 'bank_balance', 'emergency_fund', 'emi_scenario',
       'requested_amount', 'requested_tenure', 'emi_eligibility',
       'max_monthly_emi'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   age                     400000 non-null  int64
 1   gender                  400000 non-null  object
 2   marital_status          400000 non-null  object
 3   education               400000 non-null  object
 4   monthly_salary          400000 non-null  int64
 5   employment_type         400000 non-null  object
 6   years_of_employment     400000 non-null  int64
 7   company_type            400000 non-null  object
 8   house_type              400000 non-null  object
 9   monthly_rent            400000 non-null  int64
 10  family_size             400000 non-null  int64
 11  dependents              400000 non-null  int64
 12  school_fees             400000 non-null  int64
 13  college_fees            400000 non-null  int64
 14  travel_expenses         400000 non-null  int64
 15  groceries_utilities     400000 non-null  int64
 16  other_monthly_expenses  400000 non-null  int64
 17  existing_loans          400000 non-null  int64
 18  current_emi_amount      400000 non-null  int64
 19  credit_score            400000 non-null  int64
 20  bank_balance            400000 non-null  int64
 21  emergency_fund          400000 non-null  int64
 22  emi_scenario            400000 non-null  object
 23  requested_amount        400000 non-null  int64
 24  requested_tenure        400000 non-null  int64
 25  emi_eligibility         400000 non-null  object
 26  max_monthly_emi         400000 non-null  int64
dtypes: int64(19), object(8)
memory usage: 82.4+ MB

In [7]:
df.isna().sum()

age                       0
gender                    0
marital_status            0
education                 0
monthly_salary            0
employment_type           0
years_of_employment       0
company_type              0
house_type                0
monthly_rent              0
family_size               0
dependents                0
school_fees               0
college_fees              0
travel_expenses           0
groceries_utilities       0
other_monthly_expenses    0
existing_loans            0
current_emi_amount        0
credit_score              0
bank_balance              0
emergency_fund            0
emi_scenario              0
requested_amount          0
requested_tenure          0
emi_eligibility           0
max_monthly_emi           0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

,age,monthly_salary,years_of_employment,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,other_monthly_expenses,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,requested_amount,requested_tenure,max_monthly_emi
count,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.00000,400000.000000,4.000000e+05,4.000000e+05,4.000000e+05,400000.000000,400000.000000
mean,42.517025,69560.426317,17.977505,10576.298312,4.501270,1.497837,7156.888390,11464.436508,7759.671280,16482.750115,9997.551130,0.450915,6265.17836,648.999222,4.340701e+05,1.193328e+05,3.709292e+05,29.118880,7686.419895
std,10.384865,42626.070288,10.090752,15550.961952,2.293531,1.322571,6649.099868,15844.972148,4181.300818,7795.888405,5769.390762,0.497585,10143.90712,98.122254,3.793277e+05,1.285452e+05,3.443177e+05,18.083352,11981.805879
min,25.000000,15000.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,500.000000,3000.000000,0.000000,0.000000,0.00000,300.000000,7.581000e+03,4.190000e+02,1.000200e+04,3.000000,500.000000
25%,34.000000,35442.000000,9.000000,0.000000,3.000000,0.000000,0.000000,0.000000,4144.000000,9730.000000,4998.000000,0.000000,0.00000,582.000000,1.622848e+05,3.372275e+04,1.247678e+05,15.000000,500.000000
50%,43.000000,59701.000000,18.000000,0.000000,5.000000,1.000000,6042.000000,0.000000,7761.000000,16464.000000,10001.000000,0.000000,0.00000,650.000000,3.164270e+05,7.570000e+04,2.371880e+05,25.000000,500.000000
75%,52.000000,91148.000000,27.000000,20503.250000,7.000000,2.000000,13017.000000,22715.000000,11377.000000,23224.000000,14987.000000,1.000000,9294.00000,717.000000,5.918545e+05,1.568430e+05,4.948032e+05,40.000000,11004.000000
max,60.000000,229976.000000,35.000000,50000.000000,8.000000,4.000000,20000.000000,50000.000000,15000.000000,30000.000000,20000.000000,1.000000,77803.00000,850.000000,2.723349e+06,1.226379e+06,1.499977e+06,84.000000,50000.000000

# **EDA**

In [10]:
df["emi_eligibility"].value_counts()

emi_eligibility
Not_Eligible    248868
High_Risk       105198
Eligible         45934
Name: count, dtype: int64

In [11]:
df["emi_scenario"].value_counts()

emi_scenario
E-commerce         80000
Home Appliances    80000
Personal Loan      80000
Vehicle            80000
Education          80000
Name: count, dtype: int64

In [12]:
df["gender"].value_counts()

gender
Male      219500
Female    180500
Name: count, dtype: int64

In [13]:
df["education"].value_counts()

education
Graduate         159975
Post Graduate    119761
High School       79951
Professional      40313
Name: count, dtype: int64

In [14]:
df["employment_type"].value_counts()

employment_type
Private          240491
Government        99926
Self-employed     59583
Name: count, dtype: int64

In [15]:
df["house_type"].value_counts()

house_type
Rented    159837
Own       140365
Family     99798
Name: count, dtype: int64

In [16]:
df["max_monthly_emi"].describe()

count    400000.000000
mean       7686.419895
std       11981.805879
min         500.000000
25%         500.000000
50%         500.000000
75%       11004.000000
max       50000.000000
Name: max_monthly_emi, dtype: float64

In [17]:
df["credit_score"].describe()

count    400000.000000
mean        648.999222
std          98.122254
min         300.000000
25%         582.000000
50%         650.000000
75%         717.000000
max         850.000000
Name: credit_score, dtype: float64

In [18]:
df["monthly_salary"].describe()

count    400000.000000
mean      69560.426317
std       42626.070288
min       15000.000000
25%       35442.000000
50%       59701.000000
75%       91148.000000
max      229976.000000
Name: monthly_salary, dtype: float64

## Data cleaning
(drop nulls / duplicates if any, optional row sampling)

In [19]:
df = df.dropna()

In [20]:
df = df.drop_duplicates()

In [21]:
df.shape

(400000, 27)

In [22]:
df = df.sample(n=50000, random_state=42).reset_index(drop=True)

In [23]:
df.shape

(50000, 27)

In [24]:
df["emi_eligibility"].value_counts()

emi_eligibility
Not_Eligible    31190
High_Risk       12995
Eligible         5815
Name: count, dtype: int64

#Feature engineering

In [25]:
# total monthly expenses
df["total_expenses"] = (df["monthly_rent"] + df["school_fees"] + df["college_fees"]
                        + df["travel_expenses"] + df["groceries_utilities"]
                        + df["other_monthly_expenses"] + df["current_emi_amount"])

In [26]:
# disposable income = salary - total expenses
df["disposable_income"] = df["monthly_salary"] - df["total_expenses"]

In [27]:
# debt-to-income ratio
df["debt_to_income"] = df["current_emi_amount"] / df["monthly_salary"]

In [28]:
# expense-to-income ratio
df["expense_to_income"] = df["total_expenses"] / df["monthly_salary"]

In [29]:
# savings ratio (bank balance vs annual salary)
df["savings_ratio"] = df["bank_balance"] / (df["monthly_salary"] * 12)

In [30]:
# requested EMI estimate (principal / tenure)
df["requested_emi_estimate"] = df["requested_amount"] / df["requested_tenure"]

In [31]:
# requested EMI as % of salary
df["requested_emi_to_income"] = df["requested_emi_estimate"] / df["monthly_salary"]

In [32]:
df.head()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,...,requested_tenure,emi_eligibility,max_monthly_emi,total_expenses,disposable_income,debt_to_income,expense_to_income,savings_ratio,requested_emi_estimate,requested_emi_to_income
0,49,Male,Married,Post Graduate,73750,Government,22,Startup,Own,0,...,16,Eligible,5209,60726,13024,0.201464,0.823403,0.502888,47401.562500,0.642733
1,54,Male,Married,High School,29440,Private,24,Large,Own,0,...,24,Not_Eligible,500,39948,-10508,0.000000,1.356929,0.678717,508.208333,0.017263
2,54,Female,Married,Graduate,40869,Government,1,Startup,Own,0,...,18,Not_Eligible,500,62178,-21309,0.249505,1.521398,0.620996,14810.444444,0.362388
3,38,Female,Married,Professional,84724,Private,28,SME,Rented,10778,...,20,High_Risk,5835,70135,14589,0.000000,0.827806,0.788723,9509.900000,0.112246
4,30,Male,Single,Graduate,44994,Private,10,SME,Rented,38620,...,70,Not_Eligible,500,100043,-55049,0.000000,2.223474,0.749641,16069.014286,0.357137

In [33]:
df.shape

(50000, 34)

# Encode categorical columns + scale numeric columns

In [34]:
# one-hot encode the categorical columns
cat_cols = ["gender", "marital_status", "education", "employment_type",
            "company_type", "house_type", "emi_scenario"]

df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [35]:
df.head()

,age,monthly_salary,years_of_employment,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,...,employment_type_Self-employed,company_type_Large,company_type_SME,company_type_Startup,house_type_Own,house_type_Rented,emi_scenario_Education,emi_scenario_Home Appliances,emi_scenario_Personal Loan,emi_scenario_Vehicle
0,49,73750,22,0,1,0,0,0,8950,23791,...,False,False,False,True,True,False,False,False,True,False
1,54,29440,24,0,7,4,3227,1328,2514,13961,...,False,True,False,False,True,False,False,False,False,False
2,54,40869,1,0,2,1,937,0,14175,21468,...,False,False,False,True,True,False,True,False,False,False
3,38,84724,28,10778,6,1,16487,0,11314,19106,...,False,False,True,False,False,True,True,False,False,False
4,30,44994,10,38620,4,3,1647,36599,3998,4938,...,False,False,True,False,False,True,False,False,False,True

In [36]:
df.shape

(50000, 43)

In [37]:
from sklearn.preprocessing import StandardScaler

# numeric columns to scale (exclude target columns)
num_cols = ["age", "monthly_salary", "years_of_employment", "monthly_rent",
            "family_size", "dependents", "school_fees", "college_fees",
            "travel_expenses", "groceries_utilities", "other_monthly_expenses",
            "existing_loans", "current_emi_amount", "credit_score",
            "bank_balance", "emergency_fund", "requested_amount", "requested_tenure",
            "total_expenses", "disposable_income", "debt_to_income",
            "expense_to_income", "savings_ratio", "requested_emi_estimate",
            "requested_emi_to_income"]

scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

In [38]:
df.head()

,age,monthly_salary,years_of_employment,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,...,employment_type_Self-employed,company_type_Large,company_type_SME,company_type_Startup,house_type_Own,house_type_Rented,emi_scenario_Education,emi_scenario_Home Appliances,emi_scenario_Personal Loan,emi_scenario_Vehicle
0,0.628220,0.101892,0.394329,-0.678188,-1.521188,-1.128470,-1.074589,-0.723763,0.283114,0.939067,...,False,False,False,True,True,False,False,False,True,False
1,1.110123,-0.935907,0.592148,-0.678188,1.089338,1.891372,-0.588903,-0.639760,-1.257995,-0.323395,...,False,True,False,False,True,False,False,False,False,False
2,1.110123,-0.668224,-1.682773,-0.678188,-1.086100,-0.373509,-0.933564,-0.723763,1.534249,0.640726,...,False,False,False,True,True,False,True,False,False,False
3,-0.431966,0.358918,0.987786,0.013668,0.654250,-0.373509,1.406818,-0.723763,0.849178,0.337375,...,False,False,True,False,False,True,True,False,False,False
4,-1.203011,-0.571611,-0.792586,1.800888,-0.215925,1.136412,-0.826704,1.591310,-0.902649,-1.482214,...,False,False,True,False,False,True,False,False,False,True

#Step 6 — Classification: split X and y = emi_eligibility → train/test split

In [39]:
# features = all columns except the two targets
X = df.drop(columns=["emi_eligibility", "max_monthly_emi"])

# classification target
y = df["emi_eligibility"]

In [40]:
X.shape

(50000, 41)

In [41]:
y.value_counts()

emi_eligibility
Not_Eligible    31190
High_Risk       12995
Eligible         5815
Name: count, dtype: int64

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [43]:
X_train.shape, X_test.shape

((40000, 41), (10000, 41))

In [44]:
y_train.value_counts()

emi_eligibility
Not_Eligible    24952
High_Risk       10396
Eligible         4652
Name: count, dtype: int64

In [45]:
#Step 7 (train 3 classification models — Logistic Regression, Random Forest, XGBoost + classification report)

#Model 1 — Logistic Regression

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [47]:
pred_lr = lr.predict(X_test)

In [48]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

    Eligible       0.81      0.77      0.79      1163
   High_Risk       0.76      0.80      0.78      2599
Not_Eligible       0.94      0.93      0.93      6238

    accuracy                           0.88     10000
   macro avg       0.84      0.83      0.84     10000
weighted avg       0.88      0.88      0.88     10000

#Model 2 — Random Forest

In [49]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [50]:
pred_rf = rf.predict(X_test)

In [51]:
print(classification_report(y_test, pred_rf))

              precision    recall  f1-score   support

    Eligible       0.98      0.98      0.98      1163
   High_Risk       0.99      0.99      0.99      2599
Not_Eligible       1.00      1.00      1.00      6238

    accuracy                           1.00     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       1.00      1.00      1.00     10000

#Model 3 — XGBoost

In [52]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

# XGBoost needs numeric labels
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc  = le.transform(y_test)

In [53]:
xgb = XGBClassifier(random_state=42, eval_metric="mlogloss")
xgb.fit(X_train, y_train_enc)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [54]:
pred_xgb = xgb.predict(X_test)

In [55]:
print(classification_report(y_test_enc, pred_xgb, target_names=le.classes_))

              precision    recall  f1-score   support

    Eligible       1.00      0.99      1.00      1163
   High_Risk       0.99      1.00      1.00      2599
Not_Eligible       1.00      1.00      1.00      6238

    accuracy                           1.00     10000
   macro avg       1.00      1.00      1.00     10000
weighted avg       1.00      1.00      1.00     10000

# Step 8 Regression models — predict max_monthly_emi with Linear Regression, Random Forest, XGBoost + RMSE / R²

In [56]:
# regression target
y_reg = df["max_monthly_emi"]

In [57]:
from sklearn.model_selection import train_test_split

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X, y_reg, test_size=0.2, random_state=42
)

In [58]:
X_train_r.shape, X_test_r.shape

((40000, 41), (10000, 41))

Model 1 — Linear Regression

In [59]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

linr = LinearRegression()
linr.fit(X_train_r, y_train_r)

LinearRegression()

In [60]:
pred_linr = linr.predict(X_test_r)

In [61]:
rmse = np.sqrt(mean_squared_error(y_test_r, pred_linr))
r2 = r2_score(y_test_r, pred_linr)
print("RMSE:", rmse)
print("R2  :", r2)

RMSE: 3303.1014469480783
R2  : 0.9244915505739921

Model 2 — Random Forest Regressor

In [62]:
from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor(random_state=42)
rfr.fit(X_train_r, y_train_r)

RandomForestRegressor(random_state=42)

In [63]:
pred_rfr = rfr.predict(X_test_r)

In [64]:
rmse = np.sqrt(mean_squared_error(y_test_r, pred_rfr))
r2 = r2_score(y_test_r, pred_rfr)
print("RMSE:", rmse)
print("R2  :", r2)

RMSE: 2.619803998393784
R2  : 0.9999999525004682

Model 3 — XGBoost Regressor

In [65]:
from xgboost import XGBRegressor

xgbr = XGBRegressor(random_state=42)
xgbr.fit(X_train_r, y_train_r)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [66]:
pred_xgbr = xgbr.predict(X_test_r)

In [67]:
rmse = np.sqrt(mean_squared_error(y_test_r, pred_xgbr))
r2 = r2_score(y_test_r, pred_xgbr)
print("RMSE:", rmse)
print("R2  :", r2)

RMSE: 113.83694307813698
R2  : 0.999910295009613

#Step 9 (MLflow tracking — log params, metrics, and models for all the runs)

In [68]:
!pip install mlflow -q

In [69]:
import mlflow
import mlflow.sklearn
import mlflow.xgboost
from sklearn.metrics import accuracy_score, f1_score

mlflow.set_experiment("emi_prediction")

2026/04/20 08:20:17 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/04/20 08:20:17 INFO mlflow.store.db.utils: Updating database tables
2026/04/20 08:20:20 INFO mlflow.tracking.fluent: Experiment with name 'emi_prediction' does not exist. Creating a new experiment.

<Experiment: artifact_location='/content/mlruns/1', creation_time=1776673220003, experiment_id='1', last_update_time=1776673220003, lifecycle_stage='active', name='emi_prediction', tags={}, trace_location=None, workspace='default'>

In [70]:
with mlflow.start_run(run_name="LogisticRegression"):
    mlflow.log_param("max_iter", 1000)
    mlflow.log_metric("accuracy", accuracy_score(y_test, pred_lr))
    mlflow.log_metric("f1_macro", f1_score(y_test, pred_lr, average="macro"))
    mlflow.sklearn.log_model(lr, "model")

2026/04/20 08:20:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/20 08:20:41 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

In [71]:
with mlflow.start_run(run_name="RandomForestClassifier"):
    mlflow.log_param("n_estimators", rf.n_estimators)
    mlflow.log_metric("accuracy", accuracy_score(y_test, pred_rf))
    mlflow.log_metric("f1_macro", f1_score(y_test, pred_rf, average="macro"))
    mlflow.sklearn.log_model(rf, "model")

2026/04/20 08:20:56 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/20 08:20:56 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

In [72]:
with mlflow.start_run(run_name="XGBoostClassifier"):
    mlflow.log_param("n_estimators", xgb.n_estimators)
    mlflow.log_metric("accuracy", accuracy_score(y_test_enc, pred_xgb))
    mlflow.log_metric("f1_macro", f1_score(y_test_enc, pred_xgb, average="macro"))
    mlflow.xgboost.log_model(xgb, "model")

2026/04/20 08:21:11 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

In [73]:
with mlflow.start_run(run_name="LinearRegression"):
    mlflow.log_metric("rmse", np.sqrt(mean_squared_error(y_test_r, pred_linr)))
    mlflow.log_metric("r2",   r2_score(y_test_r, pred_linr))
    mlflow.sklearn.log_model(linr, "model")

2026/04/20 08:21:20 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/20 08:21:21 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

In [74]:
with mlflow.start_run(run_name="RandomForestRegressor"):
    mlflow.log_param("n_estimators", rfr.n_estimators)
    mlflow.log_metric("rmse", np.sqrt(mean_squared_error(y_test_r, pred_rfr)))
    mlflow.log_metric("r2",   r2_score(y_test_r, pred_rfr))
    mlflow.sklearn.log_model(rfr, "model")

2026/04/20 08:21:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/20 08:21:31 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

In [75]:
with mlflow.start_run(run_name="XGBoostRegressor"):
    mlflow.log_param("n_estimators", xgbr.n_estimators)
    mlflow.log_metric("rmse", np.sqrt(mean_squared_error(y_test_r, pred_xgbr)))
    mlflow.log_metric("r2",   r2_score(y_test_r, pred_xgbr))
    mlflow.xgboost.log_model(xgbr, "model")

2026/04/20 08:21:45 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

#Step 10 — Test Prediction on a Single Sample Applicant

In [76]:
sample_idx = 0
sample = X_test.iloc[[sample_idx]]   # keep it as a DataFrame (1 row)
sample

,age,monthly_salary,years_of_employment,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,...,employment_type_Self-employed,company_type_Large,company_type_SME,company_type_Startup,house_type_Own,house_type_Rented,emi_scenario_Education,emi_scenario_Home Appliances,emi_scenario_Personal Loan,emi_scenario_Vehicle
24066,0.435459,-0.826904,-1.484953,-0.678188,-1.0861,-0.373509,-0.341921,-0.723763,0.206011,1.032307,...,True,True,False,False,True,False,False,False,False,False

In [77]:
true_eligibility = y_test.iloc[sample_idx]
true_max_emi    = y_test_r.loc[sample.index[0]]
print("True emi_eligibility :", true_eligibility)
print("True max_monthly_emi :", true_max_emi)

True emi_eligibility : Not_Eligible
True max_monthly_emi : 500

Classification prediction (best model = XGBoost):predict class + probabilities

In [78]:
pred_class_enc = xgb.predict(sample)[0]
pred_class     = le.inverse_transform([pred_class_enc])[0]
pred_proba     = xgb.predict_proba(sample)[0]

print("Predicted emi_eligibility :", pred_class)
print("Class probabilities       :")
for cls, p in zip(le.classes_, pred_proba):
    print(f"  {cls:<12s} {p:.3f}")

Predicted emi_eligibility : Not_Eligible
Class probabilities       :
  Eligible     0.000
  High_Risk    0.000
  Not_Eligible 1.000

Regression prediction (best model = XGBoost Regressor):
 predict max monthly EMI

In [79]:
pred_max_emi = xgbr.predict(sample)[0]
print(f"Predicted max_monthly_emi : {pred_max_emi:,.2f}")
print(f"Actual    max_monthly_emi : {true_max_emi:,.2f}")
print(f"Absolute error            : {abs(pred_max_emi - true_max_emi):,.2f}")

Predicted max_monthly_emi : 499.34
Actual    max_monthly_emi : 500.00
Absolute error            : 0.66

In [80]:
print("=" * 55)
print("  SINGLE APPLICANT — EMI PREDICTION SUMMARY")
print("=" * 55)
print(f"  Eligibility (predicted) : {pred_class}")
print(f"  Eligibility (actual)    : {true_eligibility}")
print(f"  Max monthly EMI (pred)  : {pred_max_emi:,.2f}")
print(f"  Max monthly EMI (true)  : {true_max_emi:,.2f}")
print("=" * 55)

=======================================================
  SINGLE APPLICANT — EMI PREDICTION SUMMARY
=======================================================
  Eligibility (predicted) : Not_Eligible
  Eligibility (actual)    : Not_Eligible
  Max monthly EMI (pred)  : 499.34
  Max monthly EMI (true)  : 500.00
=======================================================